"""Initial migration.

Revision ID: 860045f5bd83
Revises: 
Create Date: 2024-11-18 17:12:15.831992

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '860045f5bd83'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ticket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=50), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('event', sa.String(length=100), nullable=False),
    sa.Column('cancellation_reason', sa.String(length=200), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.Column('promoter', sa.String(length=100), nullable=False),
    sa.Column('price_amount', sa.Float(), nullable=False),
    sa.Column('price_currency', sa.String(length=10), nullable=False),
    sa.Column('buyer_role', sa.String(length=50), nullable=False),
    sa.Column('buyer_first_name', sa.String(length=50), nullable=False),
    sa.Column('buyer_last_name', sa.String(length=50), nullable=False),
    sa.Column('buyer_postcode', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ticket')
    # ### end Alembic commands ###
