name: Simulate Webhook

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      url:
        description: 'URL of the Webhook'
        required: true
        type: string
      secret:
        description: 'Shared Secret'
        required: false
        default: 'AEeyJhbGciOiJIUzUxMiIsImlzcyI6'

jobs:
  simulate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set Webhook URL and Secret
        id: vars
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            echo "URL=${{ github.event.inputs.url }}" >> $GITHUB_ENV
            echo "SECRET=${{ github.event.inputs.secret }}" >> $GITHUB_ENV
          elif [ "${{ github.event_name }}" == "push" ]; then
            echo "URL=${{ secrets.WEBHOOK_URL }}" >> $GITHUB_ENV
            echo "SECRET=${{ secrets.PETZI_SECRET }}" >> $GITHUB_ENV
          fi

      - name: Run webhook simulator
        env:
          PETZI_SECRET: ${{ env.SECRET }}
        run: |
          python app/petzi_simulator.py "${{ secrets.WEBHOOK_URL }}" --secret "${{ secrets.PETZI_SECRET }}"
